# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubara < Formula
  desc "Kubara CLI tool for managing my Go binaries"
  homepage "https://github.com/adrherna01/kubara"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrherna01/kubara/releases/download/v0.1.2/kubara_0.1.2_darwin_amd64.tar.gz"
      sha256 "cbb4e6daa352cd058552e198500f0380a33b5dd8707ed03fc435b4a9319368f8"

      define_method(:install) do
        bin.install "kubara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrherna01/kubara/releases/download/v0.1.2/kubara_0.1.2_darwin_arm64.tar.gz"
      sha256 "6d1c15e3acc54c956130a4f3aff821994d3b6bfffe813e75db2b9962ae32bda5"

      define_method(:install) do
        bin.install "kubara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrherna01/kubara/releases/download/v0.1.2/kubara_0.1.2_linux_amd64.tar.gz"
      sha256 "ce9393e9e46da743c1060100e82fa3d4cc01bd7f26a78783f11a9b7b6f704dde"
      define_method(:install) do
        bin.install "kubara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrherna01/kubara/releases/download/v0.1.2/kubara_0.1.2_linux_arm64.tar.gz"
      sha256 "7d4546537e50ef2eceeb66f0dd49a90ebec8865fecdb5126d5488b04249f58a1"
      define_method(:install) do
        bin.install "kubara"
      end
    end
  end

  test do
    system "#{bin}/kubara", "--version"
  end
end
