# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubara < Formula
  desc "Kubara CLI tool for managing my Go binaries"
  homepage "https://github.com/adrherna01/kubara"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrherna01/kubara/releases/download/v0.1.5/kubara_0.1.5_darwin_amd64.tar.gz"
      sha256 "058b6a9aafc5d2c7c981dd2a7586b5fbcb752125a6eb909a3ee4b30ac5519faa"

      define_method(:install) do
        bin.install "kubara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrherna01/kubara/releases/download/v0.1.5/kubara_0.1.5_darwin_arm64.tar.gz"
      sha256 "456ca71712e6a20b43ea414f64f2e334d1aa2c3cbece0d15e15d9c8a658723fb"

      define_method(:install) do
        bin.install "kubara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrherna01/kubara/releases/download/v0.1.5/kubara_0.1.5_linux_amd64.tar.gz"
      sha256 "8afbc22f9f4ef5e5b570073ffbfdc74962f5dcbe207c3d36acac2b5ccacb9745"
      define_method(:install) do
        bin.install "kubara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrherna01/kubara/releases/download/v0.1.5/kubara_0.1.5_linux_arm64.tar.gz"
      sha256 "f7112b797e91f16fd23f9a82ae7f588084768d12840bfe99b48cd700a26048aa"
      define_method(:install) do
        bin.install "kubara"
      end
    end
  end

  test do
    system "#{bin}/kubara", "--version"
  end
end
