# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubara" do
  name "kubara"
  desc "Kubara CLI tool for managing my Go binaries"
  homepage "https://github.com/adrherna01/kubara"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubara"

  on_macos do
    on_intel do
      url "https://github.com/adrherna01/kubara/releases/download/v#{version}/kubara_#{version}_darwin_amd64.tar.gz"
      sha256 "e8123bfe750a34d79ae5bd79e570e7e5ea5bcf92f5149321159fcb1118d4722d"
    end
    on_arm do
      url "https://github.com/adrherna01/kubara/releases/download/v#{version}/kubara_#{version}_darwin_arm64.tar.gz"
      sha256 "a9fac4e8eda88c362ea48a49c8eb211c1859fe83790d5222b6bcbb1be0cdb4d4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/adrherna01/kubara/releases/download/v#{version}/kubara_#{version}_linux_amd64.tar.gz"
      sha256 "52d3dceac167ee17e592b53108b4f3d0d96073280a6fc1b307a99f68ccd1bdbb"
    end
    on_arm do
      url "https://github.com/adrherna01/kubara/releases/download/v#{version}/kubara_#{version}_linux_arm64.tar.gz"
      sha256 "8794b0b413f5e643b566f63866ec5db461d5a72f69c761e2e083c7531accb376"
    end
  end

  # No zap stanza required
end
