# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubara" do
  name "kubara"
  desc "Kubara CLI tool for managing my Go binaries"
  homepage "https://github.com/adrherna01/kubara"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubara"

  on_macos do
    on_intel do
      url "https://github.com/adrherna01/kubara/releases/download/v#{version}/kubara_#{version}_darwin_amd64.tar.gz"
      sha256 "bbbbc499f870f4f3ec38acff3645986e40da9c8cc55f5f5f87b82941647a28a8"
    end
    on_arm do
      url "https://github.com/adrherna01/kubara/releases/download/v#{version}/kubara_#{version}_darwin_arm64.tar.gz"
      sha256 "e303ade5db358a8bb3fdacf782087bf5138eac0cbb1ad627a20ff1ae373406f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/adrherna01/kubara/releases/download/v#{version}/kubara_#{version}_linux_amd64.tar.gz"
      sha256 "6d43deafa2545bab30aba8956b88f4aba36f2882a8d6e270f20561240325dbb5"
    end
    on_arm do
      url "https://github.com/adrherna01/kubara/releases/download/v#{version}/kubara_#{version}_linux_arm64.tar.gz"
      sha256 "3b15cbf3d17e7799e2cce4b86b793bcfcba2fb7fdbda1522ec3d28f365cbf61b"
    end
  end

  # No zap stanza required
end
